name: dart_get_up_to_speed
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lint: ^1.10.0
  lints: ^2.0.0
  freezed: ^2.1.0+1
  
dependencies: 
  build_runner: ^2.2.0
  freezed_annotation: ^2.1.0
  meta: ^1.8.0
  riverpod: ^1.0.3

